### ISSUE TITLE
Component images not showing

### ISSUE THREAD

**Issue by TimothyXAdams** [alarconm/BikeMaintenanceTracker#136]
Images on the component page are missing

**Comment by alarconm** [comment]
Tim can you elaborate on this? I'm looking at the build on my Machine and don't see any issues on the bike i already have, on a new bike or on the new bike when creating new components. Just tried it on Heroku as well and have no issues there either.

**Comment by averypierce** [comment]
Make a new bike and see if it works. I had that happening on bikes made in prior versions

**Comment by alarconm** [comment]
Ah yeah drop your tables you have old models in there I bet
